### ISSUE TITLE
sdk uncaught third Error   regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ScriptPower** [Tencent/wepy#1033]
import的es6模块文件中使用了async/await, 使用wepybuild后，在微信开发者工具中报如下错误

```
 thirdScriptError 
 sdk uncaught third Error 
 regeneratorRuntime is not defined 
 ReferenceError: regeneratorRuntime is not defined
    at http://127.0.0.1:54188/appservice/lib/king/account/loginInfo/index.js:10:46
    at http://127.0.0.1:54188/appservice/lib/king/account/loginInfo/index.js:47:2
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:54188/appservice/lib/king/account/index.js:7:18
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:54188/appservice/lib/king/index.js:8:16
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002`
```

更改wepy.config.js配置，增加了如下配置项后

```
compilers: {
    babel: {
      sourceMap: !prod,
      presets: [
        'env'
      ],
      plugins: [
        ['transform-runtime', { //导致 Cannot read property 'createTextNode' of undefined
          'helpers': false,
          'polyfill': true,
          'regenerator': true,
          'moduleName': 'babel-runtime'
        }],
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-async-to-generator'
      ]
    }
  }
```

又出现了 Cannot read property 'createTextNode' of undefined

```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'createTextNode' of undefined 
 TypeError: Cannot read property 'createTextNode' of undefined
    at module.exports (http://127.0.0.1:54188/appservice/npm/core-js/library/modules/_microtask.js:36:24)
    at http://127.0.0.1:54188/appservice/npm/core-js/library/modules/es6.promise.js:13:43
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:54188/appservice/npm/core-js/library/fn/promise.js:4:1
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:54188/appservice/npm/babel-runtime/core-js/promise.js:1:299
    at require (http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:54188/appservice/__dev__/WAService.js:18:16002`
```

小程序禁止访问直接访问window和document, 而上述/npm/core-js/library/modules/_microtask.js 中的代码为探测运行环境使用了document.createTextNode, 从而导致异常。

有谁知道如何解决么？

**Comment by Gcaufy** [comment]
你参考看看
```
wepy init standard demo
```
生成的配置看看

**Comment by ScriptPower** [comment]
就是基于 wepy init standard 创建的项目。
并且app.apy文件中已声明：
constructor () {
    super()
    this.use('requestfix') // 避免同时多请求
    this.use('promisify')  // 解决promise
  }

**Comment by ScriptPower** [comment]
就是基于 wepy init standard 创建的项目。
并且app.apy文件中已声明：
constructor () {
super()
this.use('requestfix') // 避免同时多请求
this.use('promisify') // 解决promise
}
@Gcaufy

**Comment by ScriptPower** [comment]
已解决，是app.wpy中依赖顺序导致。
```
import {isSessionOk} from '@/lib/test/await'
import 'wepy-async-function'
```
改为：
```
import 'wepy-async-function'
import {isSessionOk} from '@/lib/test/await'
```
问题解决

**Comment by cytle** [comment]
同样问题，core-js被打包进项目了

wepy版本： 1.5.8
wepy-cli: 1.5.9
