### ISSUE TITLE
尝试了下1.7.2的原生组件功能，有不少问题

### ISSUE THREAD

**Issue by rchunping** [Tencent/wepy#1046]
@Gcaufy 

```bash
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
```

####  <del>1. 在开发者工具里面，'@tag' 引入的组件都会报错</del> (调试基础库^1.6.7就正常)
```log
> [Exparser] [Error] [Component] Lifetime Method Error @ components/test#(anonymous)  VM41466:1

> TypeError: Cannot read property 'nodeId' of undefined  VM41466:1
    at A (WAService.js:12)
    at o.get (WAService.js:12)
    at o.config.created (base.js:331)
    at e.protoFunc.e.created (WAService.js:12)
    at o.safeCallback (WAService.js:10)
    at o.call (WAService.js:10)
    at Object.p.create [as createElement] (WAService.js:11)
    at e.value (WAService.js:12)
    at WAService.js:12
    at Array.forEach (<anonymous>)
```
不过能渲染出来，真机上打开调试并没有发现这种错误。

#### <del>2. 开发者工具下，组件内methods={}中的方法调用都会报错，即使foo() {}这样的空方法也不例外</del> (调试基础库^1.6.7就正常)
```log
> thirdScriptError                           VM41466:1
Cannot read property 'nodeId' of undefined;at undefined # doTap function
TypeError: Cannot read property 'nodeId' of undefined
    at A (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:5022)
    at o.value (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:5598)
    at Test.setData (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:287:41)
    at Test.$digest (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:672:26)
    at Test.$apply (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:603:26)
    at Test.doTap (http://127.0.0.1:49736/appservice/components/test.js:52:14)
    at o.config.methods.(anonymous function) (http://127.0.0.1:49736/appservice/npm/wepy/lib/base.js:316:33)
    at o.doTap (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:6228)
    at http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:10679
    at d (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:12803)
```
而且组件内 this.$apply() this.$emit() 都会报这个错误

真机环境又一切正常。

#### 3. 原生组件props中的 twoWay: true 失效

不确定这是bug还是feature

#### 4. 原生组件内再引入 非 原生子组件，数据无法传递进子组件

同样，不确定这是bug还是feature

#### 5. wx:for 循环内的原生组件，组件内computed中的方法全部失效

这同样导致组件内wepy-redux用 @connect() 导入的状态数据无法使用，
需要组件内部 this.$apply() 才能起作用
测试来看目前支持 created,ready 这两个生命周期函数，
于是在 ready() {this.$apply()} 可以部分解决这个问题

#### <del>6. 还有个问题</del> (同样设置调试基础库^1.6.7以上可解决)

```
> thirdScriptError             VM50537:1
Cannot read property '__wxspec__' of null;at pages/tlmsg/list # $list$touchMove function
TypeError: Cannot read property '__wxspec__' of null
    at h (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:13757)
    at e.value (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:15394)
    at a._updateCb (http://127.0.0.1:49736/appservice/__dev__/WAService.js:11:13147)
    at a.doUpdates (http://127.0.0.1:49736/appservice/__dev__/WAService.js:10:23310)
    at e.protoFunc.p.setData (http://127.0.0.1:49736/appservice/__dev__/WAService.js:11:16071)
    at o.value (http://127.0.0.1:49736/appservice/__dev__/WAService.js:12:5606)
    at ScrollView.setData (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:289:43)
    at ScrollView.$digest (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:672:26)
    at ScrollView.$apply (http://127.0.0.1:49736/appservice/npm/wepy/lib/component.js:603:26)
    at o.config.(anonymous function) (http://127.0.0.1:49736/appservice/npm/wepy/lib/base.js:97:17)
```

好像也跟 $apply 有关， 而且这个错误会导致所有 父->子 组件.sync传值失效 ,所有父组件更新后的值无法同步给子组件（不单单是引发这个错误的组件，其他组件传值同样失效了）

**Comment by cuijiemmx** [comment]
楼主幸苦了，写了这么多

**Comment by rchunping** [comment]
@cuijiemmx  主要错误log贴的多 :)

急着出产品，无奈被这么多坑折磨着....

**Comment by cuijiemmx** [comment]
@rchunping 是的，发现没法专注业务，一直在掉坑与爬坑途中..

**Comment by rchunping** [comment]
补充：

#### 第6点 是非原生组件的问题包括page本身， 重现代码:

```javascript
// page.wpy
<script>
// ....
data = {
a:0
}
onLoad() {
   this.a = NaN // 只要类型不对就会报错，然后所有.sync都会失效
}
</script>
```


而在@tag引入的原生组件内这样的类型不一致赋值并不会有问题

**Comment by Teemwu** [comment]
遇到props传不了值的情况，看了你这issue我都不敢升级到1.7.2了(⊙﹏⊙)

**Comment by rchunping** [comment]
@Teemwu  这个 1.7.2-alpha1 本来就是新功能测试的

**Comment by rchunping** [comment]
issue描述有更新，
我把开发者工具里面调试基础库设置到 1.6.7 或者以上报错信息就没有了 。没有了。没有了。。。。

**Comment by rchunping** [comment]
现在勉强能开始写业务功能了，个人觉得急需解决的是

1. 循环组件内computed的支持（包括wepy-redux @connect引入的）
2. 除了现在created,ready之外增加其他生命周期的支持attached,detached之类的

**Comment by Gcaufy** [comment]
@rchunping 
感谢测试意见。

官方文档中，原生组件是在基础库1.6.3中加入的。

3. 原生组件props中的 twoWay: true 失效
原生组件不支持 twoWay: true，只能通过组件事件去改变父组件。

4. 原生组件内再引入 非 原生子组件，数据无法传递进子组件
建议不要原生组件与非原生组件一起混用，在未来的版本里应该慢慢都去只支持原生组件了。


1.7.2这个版本目前只是为了解决非原生组件 在repeat下的种种问题，并且我也在同步开发2.x中。
如果上主要业务的话，为了减少踩坑，建议用1.7.1，然后避免使用repeat基本就没有什么大的问题了。

**Comment by trancelover** [comment]
最近也在采坑
1.组件 prop 无法传递 数组 这种是强需求，期待解决 
2.循环的组件中 无法使用 computed 这也是常见的情况，也期待解决。
设想：抢购列表 这样的业务场景  必定需要 循环组件中 应用  倒计时（computed）
基于目前的架构无法容易的实现。
另外对wepy的组织方式和开发方式非常的认可。
支持作者继续完善功能，解决呼声较高的问题。

**Comment by cuijiemmx** [comment]
@Gcaufy 老大幸苦了

**Comment by Gcaufy** [comment]
@rchunping 官方组件 中也没有twoWay,  Vue 2.0 中也没有twoWay, https://cn.vuejs.org/v2/guide/migration.html#twoWay-Prop-%E7%9A%84%E5%8F%82%E6%95%B0-%E7%A7%BB%E9%99%A4

所以子组件直接去改变父组件数据是不建议的。

**Comment by kala888** [comment]
@Gcaufy  如何避免使用repeat？是不是就是在repeat里面的component不要再使用其他自定义component？

**Comment by yuu2lee4** [comment]
@Gcaufy  2.0什么时候出呢 有什么特性
