### ISSUE TITLE
thirdScriptError sdk uncaught third Error Cannot set property 'Promise' of undefined

### ISSUE THREAD

**Issue by willin** [Tencent/wepy#1200]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

第三方库如 Promise 不能正确加载。

## Environment

  * Platform:  mac 开发者工具
  * Platform version: latest
  * wepy-cli version:  1.7.2-alpha2
  * wepy version: ^1.6.0
  
## Reproduce

```bash
yarn global add wepy-cli
wepy init standard weapp
cd weapp
yarn 
yarn dev
```

### Observed Results

Error Info:

```
VM1089:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot set property 'Promise' of undefined 
 TypeError: Cannot set property 'Promise' of undefined
    at http://127.0.0.1:62285/appservice/npm/wepy-async-function/index.js:15:11
    at require (http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:62285/appservice/app.js:23:1
    at require (http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:62285/appservice/appservice:1139:9
console.error @ VM1089:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:1008
window.onerror @ VM1089:1

VM1089:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'process' of undefined 
 TypeError: Cannot read property 'process' of undefined
    at http://127.0.0.1:62285/appservice/npm/lodash/_nodeUtil.js:17:46
    at require (http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:62285/appservice/npm/lodash/isTypedArray.js:5:16
    at require (http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:62285/appservice/npm/lodash/_arrayLikeKeys.js:8:20
    at require (http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:62285/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:62285/appservice/npm/lodash/keys.js:3:21
console.error @ VM1089:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:1008
window.onerror @ VM1089:1
appservice:1146 Tue Apr 10 2018 09:34:57 GMT+0800 (CST) page 编译错误
VM1089:1 pages/index.js 出现脚本错误或者未正确调用 Page()
```

**Comment by xiaomiwujiecao** [comment]
me too

**Comment by WangXiZhu** [comment]
同样遇到这个问题，之前没人反馈吗? 其他的错误还是有的
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'process' of undefined 
 TypeError: Cannot read property 'process' of undefined
    at http://127.0.0.1:57474/appservice/npm/lodash/_nodeUtil.js:17:46
    at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:57474/appservice/npm/lodash/isTypedArray.js:5:16
    at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:57474/appservice/npm/lodash/_arrayLikeKeys.js:8:20
    at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:57474/appservice/npm/lodash/keys.js:3:21
```

**Comment by zhuyunxiang** [comment]
开发者工具里面把 ES6 转 ES5开关关掉

**Comment by willin** [comment]
按照 Getting  Start 教程是关过的

**Comment by smithyj** [comment]
bug 一堆 唉

**Comment by ylksty** [comment]
[Error] Error: 找不到模块: util
被依赖于: .../node_modules/lodash/_nodeUtil.js。
请尝试手动执行 npm install util 进行安装。

我是这么解决的
1.还原.wepycache
2.npm install util

**Comment by justinzpc** [comment]
我一样的错 请问现在有解决办法了吗？

**Comment by tylerrrkd** [comment]
@zhuyunxiang 谢谢大牛！

**Comment by lizongze** [comment]
> 同样遇到这个问题，之前没人反馈吗? 其他的错误还是有的
> 
> ```
> thirdScriptError 
>  sdk uncaught third Error 
>  Cannot read property 'process' of undefined 
>  TypeError: Cannot read property 'process' of undefined
>     at http://127.0.0.1:57474/appservice/npm/lodash/_nodeUtil.js:17:46
>     at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
>     at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
>     at http://127.0.0.1:57474/appservice/npm/lodash/isTypedArray.js:5:16
>     at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
>     at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
>     at http://127.0.0.1:57474/appservice/npm/lodash/_arrayLikeKeys.js:8:20
>     at require (http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26712)
>     at http://127.0.0.1:57474/appservice/__dev__/WAService.js:18:26461
>     at http://127.0.0.1:57474/appservice/npm/lodash/keys.js:3:21
> ```

在项目设置里面将 `调试基础库`换到`2.4.3`或者最新版，我这里就没有这个问题了
