### ISSUE TITLE
wepy-cli 1.740版本生成web版本的问题

### ISSUE THREAD

**Issue by dengbaoling** [Tencent/wepy#1261]
## Description
 目前就是把用wepy做的小程序转web 
在转换成过程中就报wepy_cli报错
  
  [Description of the issue]

## Environment
  * wepy-cli version:1.7.1

  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]

**Comment by dengbaoling** [comment]
转换过程中报错的问题

> `C:\Users\Administrator\Desktop\项目\wepy_video\wepy_video>wepy build --output  web
[11:04:56] 编译 WEB
[11:04:56] [写入] HTML: web\index.html
[11:04:56] [编译] 入口: app.wpy
[11:04:56] [编译] WPY : src\app.wpy
[11:04:56] [编译] WPY : src\pages\index.wpy
[11:04:56] [编译] WPY : src\pages\play.wpy
[11:04:57] [拷贝] PNG : src\images\love.png
[11:04:57] [拷贝] PNG : src\images\play.png
[11:04:57] [拷贝] PNG : src\images\plays.png
[11:04:57] [拷贝] PNG : src\images\share.png
TypeError: Cannot read property 'modulePath' of undefined
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\web\compile-script.js:116:54
    at String.replace (<anonymous>)
    at Object.resolveMap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\web\compile-script.js:53:43)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\web\compile-script.js:198:34
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

C:\Users\Administrator\Desktop\项目\wepy_video\wepy_video>
`

**Comment by dengbaoling** [comment]
有大神遇到吗

**Comment by jingxinxin** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/6293249/42240573-479a174a-7f3a-11e8-8bb0-69722069f25d.png)

**Comment by margox** [comment]
同样问题，有人解决了么？
