### ISSUE TITLE
按照官方教程 npm run dev 后报错

### ISSUE THREAD

**Issue by smithyj** [Tencent/wepy#1275]
```
[Error] Error: 找不到模块: util
被依赖于: /Users/yyj/Docker/wwwroot/yangyj-wxapp/node_modules/lodash/_nodeUtil.js。
请尝试手动执行 npm install util 进行安装。
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:98:31
    at String.replace (<anonymous>)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:270:27
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

```

**Comment by linkdesu** [comment]
跟 #1276 问题一样。
