### ISSUE TITLE
 Error: module "npm/lodash/_nodeUtil.js" is not defined

### ISSUE THREAD

**Issue by Liqiankun** [Tencent/wepy#1294]
```
VM364:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/lodash/_nodeUtil.js" is not defined 
 Error: module "npm/lodash/_nodeUtil.js" is not defined
    at require (http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:27142)
    at http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:62357/appservice/npm/lodash/isTypedArray.js:3:16
    at require (http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:62357/appservice/npm/lodash/_arrayLikeKeys.js:6:20
    at require (http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:62357/appservice/npm/lodash/keys.js:1:271
    at require (http://127.0.0.1:62357/appservice/__dev__/WAService.js:18:27248)
```
"wepy": "^1.6.0"
"lodash": "^4.17.5"

**Comment by liyang007700** [comment]
try "npm i util --no-save && wepy build --no-cache", it helps for me!

**Comment by notedit** [comment]
发现wepy 在编译的时候 会丢失一些依赖中的二级目录

**Comment by towry** [comment]
`rm .wepycache` 然后重新build。
