### ISSUE TITLE
wepy 编译时把注释也加入编译了

### ISSUE THREAD

**Issue by growold** [Tencent/wepy#1410]
## Description

  wepy build 会把代码注释中的require代码也进行编译
  如果在代码注释中写入:require('testtest')
  编译的时候会报如下的错误
[Error] Error: 找不到模块: testtest
被依赖于: /Users/**/Documents/wepy-test/src/mixins/test.js。
请尝试手动执行 npm install testtest 进行安装。
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:98:31
    at String.replace (<anonymous>)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:270:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

## Environment

  * wepy-cli version: 1.7.2
  * wepy version: 1.7.1

**Comment by ystarlongzi** [comment]
wepy-cli 升级到 `1.7.2-alpha2`
