### ISSUE TITLE
[Bug]通过npm无法升级到1.7.2

### ISSUE THREAD

**Issue by liuyangcharlie** [Tencent/wepy#1464]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]
通过`npm`无法升级到1.7.2

## Environment

  * Platform: Mac
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: 1.7.2
  * wepy version: 1.7.1
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]
1. 修改package.json中的wepy版本为1.7.2或1.7.2-alpha[2-4]
2. 执行`npm install`

### Observed Results

  [实际表现]
  
  [Observed Results]
![image](https://user-images.githubusercontent.com/6851070/41255692-f51035c8-6df9-11e8-8da8-6004a384d836.png)

  
### Expected Results

  [期望表现]
  
  [Expected Results]
1.7.2安装成功
  

## Relevant Code / Logs
npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData wepy
20 silly mapToRegistry name wepy
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'wepy',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'wepy',
23 silly mapToRegistry   name: 'wepy',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/wepy
25 verbose request uri https://registry.npmjs.org/wepy
26 verbose request no auth needed
27 info attempt registry request try #1 at 4:23:16 AM
28 verbose request id bd367084e5783b33
29 verbose etag W/"37619d499efdb3a9aac8cb98658e774c"
30 verbose lastModified Sun, 27 May 2018 21:54:48 GMT
31 http request GET https://registry.npmjs.org/wepy
32 http 304 https://registry.npmjs.org/wepy
33 verbose headers { date: 'Mon, 11 Jun 2018 20:23:16 GMT',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'set-cookie': [ '__cfduid=d4406820206d74180e11673d9394fdac11528748596; expires=Tue, 11-Jun-19 20:23:16 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
33 verbose headers   'cache-control': 'max-age=300',
33 verbose headers   'cf-cache-status': 'HIT',
33 verbose headers   'cf-ray': '4296cb679b6db14c-HKG',
33 verbose headers   etag: '"37619d499efdb3a9aac8cb98658e774c"',
33 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
33 verbose headers   'last-modified': 'Sun, 27 May 2018 21:54:48 GMT',
33 verbose headers   vary: 'accept-encoding, accept',
33 verbose headers   server: 'cloudflare' }
34 silly get cb [ 304,
34 silly get   { date: 'Mon, 11 Jun 2018 20:23:16 GMT',
34 silly get     connection: 'keep-alive',
34 silly get     'set-cookie': [ '__cfduid=d4406820206d74180e11673d9394fdac11528748596; expires=Tue, 11-Jun-19 20:23:16 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
34 silly get     'cache-control': 'max-age=300',
34 silly get     'cf-cache-status': 'HIT',
34 silly get     'cf-ray': '4296cb679b6db14c-HKG',
34 silly get     etag: '"37619d499efdb3a9aac8cb98658e774c"',
34 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
34 silly get     'last-modified': 'Sun, 27 May 2018 21:54:48 GMT',
34 silly get     vary: 'accept-encoding, accept',
34 silly get     server: 'cloudflare' } ]
35 verbose etag https://registry.npmjs.org/wepy from cache
36 verbose get saving wepy to /Users/yangliu/.npm/registry.npmjs.org/wepy/.cache.json
37 verbose correctMkdir /Users/yangliu/.npm correctMkdir not in flight; initializing
38 silly fetchNamedPackageData No valid target from cache, forcing network
39 verbose request uri https://registry.npmjs.org/wepy
40 verbose request no auth needed
41 info attempt registry request try #1 at 4:23:16 AM
42 http request GET https://registry.npmjs.org/wepy
43 http 200 https://registry.npmjs.org/wepy
44 verbose headers { date: 'Mon, 11 Jun 2018 20:23:16 GMT',
44 verbose headers   'content-type': 'application/json; charset=UTF-8',
44 verbose headers   'transfer-encoding': 'chunked',
44 verbose headers   connection: 'keep-alive',
44 verbose headers   'set-cookie': [ '__cfduid=d4406820206d74180e11673d9394fdac11528748596; expires=Tue, 11-Jun-19 20:23:16 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
44 verbose headers   'cache-control': 'max-age=300',
44 verbose headers   'cf-cache-status': 'HIT',
44 verbose headers   'cf-ray': '4296cb686b7bb14c-HKG',
44 verbose headers   etag: 'W/"37619d499efdb3a9aac8cb98658e774c"',
44 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
44 verbose headers   'last-modified': 'Sun, 27 May 2018 21:54:48 GMT',
44 verbose headers   vary: 'accept-encoding, accept',
44 verbose headers   server: 'cloudflare',
44 verbose headers   'content-encoding': 'gzip' }
45 silly get cb [ 200,
45 silly get   { date: 'Mon, 11 Jun 2018 20:23:16 GMT',
45 silly get     'content-type': 'application/json; charset=UTF-8',
45 silly get     'transfer-encoding': 'chunked',
45 silly get     connection: 'keep-alive',
45 silly get     'set-cookie': [ '__cfduid=d4406820206d74180e11673d9394fdac11528748596; expires=Tue, 11-Jun-19 20:23:16 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
45 silly get     'cache-control': 'max-age=300',
45 silly get     'cf-cache-status': 'HIT',
45 silly get     'cf-ray': '4296cb686b7bb14c-HKG',
45 silly get     etag: 'W/"37619d499efdb3a9aac8cb98658e774c"',
45 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
45 silly get     'last-modified': 'Sun, 27 May 2018 21:54:48 GMT',
45 silly get     vary: 'accept-encoding, accept',
45 silly get     server: 'cloudflare',
45 silly get     'content-encoding': 'gzip' } ]
46 verbose get saving wepy to /Users/yangliu/.npm/registry.npmjs.org/wepy/.cache.json
47 verbose correctMkdir /Users/yangliu/.npm correctMkdir not in flight; initializing
48 silly fetchPackageMetaData Error: No compatible version found: wepy@^1.7.2-alpha4
48 silly fetchPackageMetaData Valid install targets:
48 silly fetchPackageMetaData 1.7.2-alpha1, 1.7.1, 1.7.0, 1.6.1-alpha3, 1.6.1-alpha2, 1.6.1-alpha1, 1.6.0, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.1, 1.3.11, 1.3.10, 1.3.9, 1.3.6, 1.3.3, 1.3.2, 1.2.6, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 0.0.2, 0.0.1
48 silly fetchPackageMetaData
48 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
48 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
48 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15)
48 silly fetchPackageMetaData  error for wepy@^1.7.2-alpha4 { Error: No compatible version found: wepy@^1.7.2-alpha4
48 silly fetchPackageMetaData Valid install targets:
48 silly fetchPackageMetaData 1.7.2-alpha1, 1.7.1, 1.7.0, 1.6.1-alpha3, 1.6.1-alpha2, 1.6.1-alpha1, 1.6.0, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.1, 1.3.11, 1.3.10, 1.3.9, 1.3.6, 1.3.3, 1.3.2, 1.2.6, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 0.0.2, 0.0.1
48 silly fetchPackageMetaData
48 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
48 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
48 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
48 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ETARGET' }
49 silly rollbackFailedOptional Starting
50 silly rollbackFailedOptional Finishing
51 silly runTopLevelLifecycles Finishing
52 silly install printInstalled
53 verbose stack Error: No compatible version found: wepy@^1.7.2-alpha4
53 verbose stack Valid install targets:
53 verbose stack 1.7.2-alpha1, 1.7.1, 1.7.0, 1.6.1-alpha3, 1.6.1-alpha2, 1.6.1-alpha1, 1.6.0, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.1, 1.3.11, 1.3.10, 1.3.9, 1.3.6, 1.3.3, 1.3.2, 1.2.6, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 0.0.2, 0.0.1
53 verbose stack
53 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:178:16)
53 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
53 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
53 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
53 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
53 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
54 verbose cwd /Users/yangliu/Documents/Code/test/toys/mini_program/taxi/ui
55 error Darwin 16.5.0
56 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
57 error node v6.11.2
58 error npm  v3.10.10
59 error code ETARGET
60 error notarget No compatible version found: wepy@^1.7.2-alpha4
60 error notarget Valid install targets:
60 error notarget 1.7.2-alpha1, 1.7.1, 1.7.0, 1.6.1-alpha3, 1.6.1-alpha2, 1.6.1-alpha1, 1.6.0, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.1, 1.3.11, 1.3.10, 1.3.9, 1.3.6, 1.3.3, 1.3.2, 1.2.6, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 0.0.2, 0.0.1
61 error notarget This is most likely not a problem with npm itself.
61 error notarget In most cases you or one of your dependencies are requesting
61 error notarget a package version that doesn't exist.
61 error notarget
61 error notarget It was specified as a dependency of 'taxi'
62 verbose exit [ 1, true ]
```

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by BoleLee** [comment]
大约`wepy1.7.2`还没有正式发布，虽然`wepy-cli 1.7.2`早就发布了，但它们经常不同步，文档也不会说明

**Comment by Gcaufy** [comment]
changelog 中提到的版本主要是以 wepy-cli 版本为主，wepy-cli 升级时，如果有依赖 wepy 的话，在升级 wepy-cli 后编译时会自动升级 wepy。如果不依赖 wepy时，则不会要求升级 wepy. 因此会经常出现 wepy 版本比 cli 版本低的情况，这个是正常的。

如果想了解版本信息的话，可以用
```
npm info wepy
npm info wepy-cli
```
去查询
