### ISSUE TITLE
Cannot read property '$wxapp' of undefined

### ISSUE THREAD

**Issue by fonglezen** [Tencent/wepy#1516]
## Description

  在pages目录内创建一个新wpy页面：task.wpy，运行报错：
  
 ```
thirdScriptError
Cannot read property '$wxapp' of undefined;at pages/task page lifeCycleMethod onLoad function
TypeError: Cannot read property '$wxapp' of undefined
    at Task.$init (http://127.0.0.1:32579/appservice/npm/wepy/lib/component.js:118:49)
    at e.config.onLoad (http://127.0.0.1:32579/appservice/npm/wepy/lib/base.js:156:18)
    at e.<anonymous> (http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:27674)
    at q (http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:9110)
    at Z (http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:11143)
    at te (http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:11413)
    at Function.<anonymous> (http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:14157)
    at http://127.0.0.1:32579/appservice/__dev__/WAService.js:1:19990
    at http://127.0.0.1:32579/appservice/__dev__/WAService.js:8:19668
    at Array.forEach (<anonymous>)
 ```

## Environment

  * Platform: 微信开发者工具，vscode
  * Platform version: 微信开发者工具1.02，vscode 1.24.1
  * wepy-cli version: 1.7.2
  * wepy version: 1.7.2
  
## Reproduce
根据我贴的代码，通过wepy init standard 之后，在pages新增task.wpy；
在app.wpy中修改：
config.pages改为['pages/task']

### Observed Results
报错 Cannot read property '$wxapp' of undefined
  
### Expected Results
没报错，通过。
  

## Relevant Code / Logs

  ```
  <style lang="less" scoped>
    .date-now {
        width: 100%;
        padding: 20px;
        box-sizing: border-box;
    }
</style>


<template>
    <view class="container">
        <view class="date-now main-bg-color white-text">
            {{text}}
            {{now_date}}
            {{now_day}}
        </view>
    </view>
</template>

<script>
    import wepy from 'wepy';

    export default class Task extends wepy.component {
        getNowDate () {
            let now = new Date();
            this.now_date = `${now.getFullYear()}-${now.getMonth() + 1}-${now.getDate()}`;
            this.now_day = `星期 ${now.getDay()}`;
        }

        onShow () {
           
        }  // 只在Page中存在的页面生命周期函数

        onLoad () {
            console.log('onLoad');
            this.getNowDate();
        }
        
        config = {
            navigationBarBackgroundColor: '#49c77c',
            navigationBarTitleText: '',
            navigationBarTextStyle: '#ffffff',
        };  // 只在Page实例中存在的配置数据，对应于原生的page.json文件

        data = {
            text: 'aaa',
            now_date: 'xxx',
            now_day: 'xxx'
        };  // 页面所需数据均需在这里声明，可用于模板数据绑定

    }
</script>


  ```

**Comment by fonglezen** [comment]
应该是extends  wepy.page ,抱歉打扰了。。。

**Comment by chengqiang1992** [comment]
您好，请问您这个问题解决了吗？ 是怎么解决的？

**Comment by adwerrd** [comment]
> 您好，请问您这个问题解决了吗？ 是怎么解决的？
将
```
export default class Task extends wepy.component
```
改成
```
export default class Task extends wepy.page
```
