### ISSUE TITLE
promise 启用报错

### ISSUE THREAD

**Issue by 316boss** [Tencent/wepy#1707]
一启用 promise 就报错
```
thirdScriptError 
 sdk uncaught third Error 
 addon is not a constructor 
 TypeError: addon is not a constructor
    at _default.use (http://127.0.0.1:61338/appservice/npm/wepy/lib/app.js:92:44)
    at new _default (http://127.0.0.1:61338/appservice/app.js:81:11)
    at Object.$createApp (http://127.0.0.1:61338/appservice/npm/wepy/lib/base.js:105:19)
    at http://127.0.0.1:61338/appservice/app.js:150:47
    at require (http://127.0.0.1:61338/appservice/__dev__/WAService.js:22:19384)
    at http://127.0.0.1:61338/appservice/appservice?t=1534774102986:1121:9
console.error @ VM12223:1
(anonymous) @ WAService.js:14
(anonymous) @ WAService.js:6
a @ appservice?t=1534774102986:1018
window.onerror @ VM12223:1
index.js? [sm]:12 moduleA ignored:  {}
VM12223:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:61338/appservice/npm/wepy/lib/base.js:142:27)
    at http://127.0.0.1:61338/appservice/pages/index.js:236:51
    at require (http://127.0.0.1:61338/appservice/__dev__/WAService.js:22:19384)
    at http://127.0.0.1:61338/appservice/appservice?t=1534774102986:1125:9
console.error @ VM12223:1
(anonymous) @ WAService.js:14
(anonymous) @ WAService.js:6
a @ appservice?t=1534774102986:1018
window.onerror @ VM12223:1

```

已经关闭 es6

重新初始过了

手动安装 util 过了

仍然报错

**Comment by 316boss** [comment]
在 npm install wepy-async-function --save 有这样的提示，不知道有没有关系
found 4 moderate severity vulnerabilities

npm audit 的结果

───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wepy-compiler-less [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wepy-compiler-less > less > request > hawk > boom > hoek     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wepy-compiler-less [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wepy-compiler-less > less > request > hawk > cryptiles >     │
│               │ boom > hoek                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wepy-compiler-less [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wepy-compiler-less > less > request > hawk > hoek            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wepy-compiler-less [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wepy-compiler-less > less > request > hawk > sntp > hoek     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by 316boss** [comment]
发现问题了，promisify  字符串写错了。。。 可这报错也太奇怪了
