### ISSUE TITLE
Error: ENOSPC: no space left on device, watch 'src/mixins'

### ISSUE THREAD

**Issue by 316boss** [Tencent/wepy#1838]
执行 wepy build --no-cache --watch 时报错：

所有目录磁盘空间充足

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: no space left on device, watch 'src/mixins'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1218:11)
    at createFsWatchInstance (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/index.js:257:10)
    at createFsWatchInstance (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/xujifa/.nvm/versions/node/v10.8.0/lib/node_modules/wepy-cli/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by 316boss** [comment]
解决了，和 wepy 没有关系，系统设置问题
