### ISSUE TITLE
cli生成的项目运行npm run build后，js代码没有压缩

### ISSUE THREAD

**Issue by dtboy1995** [Tencent/wepy#1860]
`npm run build`后
log如下
```
cross-env NODE_ENV=production wepy build --no-cache

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at Module.require (internal/modules/cjs/loader.js:631:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.load (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\loader.js:113:17)
    at Object.loadPlugin (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\loader.js:131:24)
    at Object.checkPlugin (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile.js:187:33)
    at Object.init (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile.js:221:60)
    at Command.module.exports (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\bin\wepy-build.js:11:24)
    at Command.listener (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\dtboy\AppData\Roaming\npm\node_modules\wepy-cli\lib\bin\wepy.js:44:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[02:50:20] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
npm WARN airquality@0.0.2 No repository field.

up to date in 4.115s
[02:50:26] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
[WARNING] WARNING IN : src\pages\bind\small\transmit.wpy
[xmldom warning]        attribute "true" missed quot(")!!
@#[line:106,col:7]
[02:50:26] [编译] 入口: src\app.wpy
...............
...............
```
运行结束后到dist/目录下查看js文件都没有压缩?请问一下是什么问题，谢谢了

**Comment by dtboy1995** [comment]
https://github.com/Tencent/wepy/issues/1134
