### ISSUE TITLE
wepy-redux初始化遇到问题

### ISSUE THREAD

**Issue by QinZhen001** [Tencent/wepy#1942]
## Description

模仿官方模板引入wepy-redux初始化时遇到问题
  
```
VM5557:1 thirdScriptError 
 sdk uncaught third Error 
 module "store/reducers/counter.js" is not defined 
 Error: module "store/reducers/counter.js" is not defined
    at require (http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716408)
    at http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:23557/appservice/store/reducers/index.js:10:16
    at require (http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716549)
    at http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:23557/appservice/store/index.js:15:17
    at require (http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716549)
    at http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:23557/appservice/app.js:18:14
    at require (http://127.0.0.1:23557/appservice/__dev__/WAService.js:1:716549)
```

package.json
```
  "dependencies": {
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",
    "redux-promise": "^0.5.3",
    "wepy": "^1.7.2-alpha3",
    "wepy-async-function": "^1.4.4",
    "wepy-redux": "^1.5.3"
  }
```

**Comment by QinZhen001** [comment]
已解决 
是plugins的问题

```
    plugins: [
        // 'babel-plugin-transform-class-properties',
        'syntax-export-extensions',
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions'
      ]
```
