### ISSUE TITLE
wepy-config 有类似 webpack alias 插件吗?

### ISSUE THREAD

**Issue by RobGu** [Tencent/wepy#203]
如果把 demo 中代码
```
  import List from '../components/list'
  import Panel from '../components/panel'
  import Counter from '../components/counter'
  import Group from '../components/group'
```
 改成 
```
  import List from 'list'
  import Panel from 'panel'
  import Counter from 'counter'
  import Group from 'group'
```

编译时提示找不到模块
```
[13:05:02] [编译] 页面: src/pages/index.wpy
[13:05:02] [写入] 配置: dist/pages/index.json
[13:05:02] [写入] JS  : dist/app.js
[13:05:02] [写入] JS  : dist/components/counter.js
[13:05:02] [写入] JS  : dist/components/group.js
[13:05:02] [写入] JS  : dist/components/groupitem.js
[13:05:02] [写入] JS  : dist/components/list.js
[13:05:02] [写入] JS  : dist/components/panel.js
[13:05:02] [写入] JS  : dist/mixins/test.js
[13:05:03] [写入] WXML: dist/pages/index.wxml
Error: 找不到模块: list
    at /Users/user/Documents/wepy-demo/node_modules/wepy-cli/lib/compile-script.js:75:31
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.resolveDeps (/Users/user/Documents/wepy-demo/node_modules/wepy-cli/lib/compile-script.js:54:21)
    at /Users/user/Documents/wepy-demo/node_modules/wepy-cli/lib/compile-script.js:205:27
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
[13:05:03] [写入] WXSS: dist/app.wxss
[13:05:03] [写入] WXSS: dist/components/counter.wxss
[13:05:03] [写入] WXSS: dist/components/group.wxss
[13:05:03] [写入] WXSS: dist/components/groupitem.wxss
[13:05:03] [写入] WXSS: dist/components/list.wxss
[13:05:03] [写入] WXSS: dist/components/panel.wxss
[13:05:03] [写入] WXSS: dist/pages/index.wxss
```

Refs
------------
https://webpack.js.org/configuration/resolve/#resolve-alias

**Comment by Gcaufy** [comment]
没有，但是可以实现，我看了一下，实现难度不大。

**Comment by cytle** [comment]
可以使用 [babel的alias插件](https://github.com/tleunen/babel-plugin-module-resolver),在`wepy.config.js`中配置如下
 
```js
const path = require('path');

module.exports = {
    compilers: {
        babel: {
            plugins: [
                [
                    'module-resolver',
                    [
                        'alias': {
                            'ALIAS_A': './src/a',
                            'ALIAS_B': './src/b.js',
                            'ALIAS_WEPY': 'wepy'
                        }
                    ]
                ]
            ]
        }
    }
// ...
};
```

**Comment by chocking** [comment]
@cytle  是我打开方式不对吗，（例）a.js中的import语句匹配到alias的时候为什么不是以wepy.config.js所在目录为起点查找，而是以a.js所在目录为起点- -

**Comment by leenty** [comment]
别名现在支持完整的文件路径名，还不支持文件夹路径的别名是嘛？
比如像这样：
```
  alias: {
    counter: path.join(__dirname, 'src/components/counter'),
    '@': path.resolve(__dirname, 'src/components/') // 这个路径直接指向组件文件夹
  }
```
然后使用的时候就可以直接这样引用
```
  import Counter from '@/counter'
```
有了就完美了👏🏻

**Comment by minzhang2** [comment]
同楼上，能实现就好了 @Gcaufy

**Comment by Gcaufy** [comment]
@leenty 支持的。。参考这里。。
https://webpack.js.org/configuration/resolve/#resolve-alias

功能与这里保持一致

**Comment by leenty** [comment]
好的，多谢😉

**Comment by githbq** [comment]
wepy.config.js 配置      resolve.alias={'@':'@': path.join(__dirname, 'src')}

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/452

**Comment by leeyeh** [comment]
@Gcaufy 请问能考虑下支持 aliasFields 选项吗？ 

https://webpack.js.org/configuration/resolve/#resolve-alias

如果需要我可以新开一个 issue。

**Comment by Gcaufy** [comment]
有什么场景么？
