### ISSUE TITLE
2.0.0-alpha.8 version not working

### ISSUE THREAD

**Issue by UZIhuhuhu** [Tencent/wepy#2160]
## Description

 `2.0.0-alpha.8` 版本遇到错误，无法使用

`2.0.0-alpha.8` version encountered an error and cannot be used
  
## Reproduce

  输入 `wepy` 遇到如下报错

```js
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '../lib/bin/wepy.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/huangxingyuan/.config/yarn/global/node_modules/wepy-cli/bin/wepy.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

## Relevant Code / Logs

报错中的 `wepy-cli/bin/wepy.js` 是 分支 `1.7.x` 中所对应的代码

```js
require('../lib/bin/wepy.js');
```

可能是你们发错版本了

**Comment by Gcaufy** [comment]
是安装方法错了吧。这样试试

```
npm i @wepy/cli@2.0.0-alpha.8 -g
```
