### ISSUE TITLE
_core.default is not a constructor 

### ISSUE THREAD

**Issue by cielu** [Tencent/wepy#2201]
thirdScriptError 
 sdk uncaught third Error 
 _core.default is not a constructor 
 TypeError: _core.default is not a constructor
    at http://127.0.0.1:60174/appservice/common/eventHub.js:14:16
    at require (http://127.0.0.1:60174/appservice/__dev__/WAService.js:1:1113027)
    at http://127.0.0.1:60174/appservice/__dev__/WAService.js:1:1112637
    at http://127.0.0.1:60174/appservice/app.js:7:40
    at require (http://127.0.0.1:60174/appservice/__dev__/WAService.js:1:1113027)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:60174/appservice/appservice?t=1561042240005:1401:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:60174/appservice/appservice?t=1561042240005:1413:20)

**Comment by Gcaufy** [comment]
缺少版本信息和代码片段，无法定位

**Comment by cielu** [comment]
> 缺少版本信息和代码片段，无法定位

就是最新版的，@wepy/core 2.0.0-alpha
使用第三方包的时候就会报这个错
```
    pages: [
      'pages/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    },
    usingComponents: {
    'van-nav-bar': '../node_modules/vant-weapp/lib/nav-bar/index'
    },
```

**Comment by Gcaufy** [comment]
第三方包的引用方式如下：

```
usingComponents: {
    'van-nav-bar': 'module:vant-weapp/lib/nav-bar/index'
}
```

**Comment by cielu** [comment]
> 第三方包的引用方式如下：
> 
> ```
> usingComponents: {
>     'van-nav-bar': 'module:vant-weapp/lib/nav-bar/index'
> }
> ```

@Gcaufy 谢谢

**Comment by cielu** [comment]
@Gcaufy  不过好像还有个bug，就是我新建的文件夹他没给我搞过去，就比如images ，生成的时候自动忽略了它

**Comment by cielu** [comment]
@Gcaufy  好像还是一样的。。

![image](https://user-images.githubusercontent.com/13715811/59974911-1477fa00-95e4-11e9-9ba1-250639cfb721.png)

**Comment by cielu** [comment]
![image](https://user-images.githubusercontent.com/13715811/59975128-2b6c1b80-95e7-11e9-9961-8cf6f40510dc.png)

**Comment by cielu** [comment]
在app里面全局引用组建的时候，好像没有导入进来

**Comment by cielu** [comment]
![image](https://user-images.githubusercontent.com/13715811/59975295-64a58b00-95e9-11e9-815a-3ab60785b646.png)

**Comment by cielu** [comment]
![image](https://user-images.githubusercontent.com/13715811/59975331-cb2aa900-95e9-11e9-8593-bc94a134489f.png)

**Comment by cielu** [comment]
改为原有写法正常
![image](https://user-images.githubusercontent.com/13715811/59975774-602fa100-95ee-11e9-930c-6b646135629a.png)

![image](https://user-images.githubusercontent.com/13715811/59975778-73db0780-95ee-11e9-8783-9087a195b14f.png)

**Comment by Gcaufy** [comment]
> @Gcaufy 不过好像还有个bug，就是我新建的文件夹他没给我搞过去，就比如images ，生成的时候自动忽略了它

https://wepyjs.github.io/wepy-docs/2.x/#/cli/config?id=static

静态资源配置一下 static 选项。

**Comment by Gcaufy** [comment]
@cielu wxs 的引用问题在最近的版本中已经fix
https://github.com/Tencent/wepy/issues/2069

**Comment by cielu** [comment]
@Gcaufy 我是用的12版的，但是还有这问题啊。。。

另外使用全局组建 ，组建不会导入到 $vendor 文件夹里面啊

**Comment by laravuel** [comment]
> @Gcaufy 我是用的12版的，但是还有这问题啊。。。
> 
> 另外使用全局组建 ，组建不会导入到 $vendor 文件夹里面啊

vant可以正常引入的，你@wepy/cli要升级到最新版本`2.0.0-alpha.12`，我刚开始也遇见你这个问题了，现在正常

**Comment by cielu** [comment]
@Gcaufy 引入全局组件未导入的问题呢？其他的好像正常了
![image](https://user-images.githubusercontent.com/13715811/59975128-2b6c1b80-95e7-11e9-9961-8cf6f40510dc.png)

**Comment by cielu** [comment]
![image](https://user-images.githubusercontent.com/13715811/60107799-1aafd700-979a-11e9-929a-eb4a7f259e37.png)

@Gcaufy  还是这个问题，不知道哪里出现的，
这个
```
var eventHub = new _core["default"]();
var _default = eventHub;
exports["default"] = _default;
```
改成
```
exports["default"] = _core["default"];
```
就正常了
