### ISSUE TITLE
引入lodash， dev 环境报错

### ISSUE THREAD

**Issue by ChrisDowney1996** [Tencent/wepy#2209]
"dependencies": {
    "@wepy/core": "^2.0.0-alpha.8",
    "@wepy/x": "^2.0.2",
    "crypto-js": "^3.1.9-1",
    "dayjs": "^1.8.14",
    "decimal.js": "^10.2.0",
    "lodash": "^4.17.11",
    "miniprogram-slide-view": "0.0.3",
    "vuex": "^3.1.1"
  }

我引入了 lodash ，npm run dev 运行出错，微信开发者工具控制台错误信息：
VM1511:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'prototype' of undefined 
 TypeError: Cannot read property 'prototype' of undefined
    at runInContext (http://127.0.0.1:17996/appservice/vendor.js:5785:27)
    at Object.<anonymous> (http://127.0.0.1:17996/appservice/vendor.js:21444:11)
    at Object.EXP_LIMIT (http://127.0.0.1:17996/appservice/vendor.js:21471:3)
    at __wepy_require (http://127.0.0.1:17996/appservice/vendor.js:20:26)
    at http://127.0.0.1:17996/appservice/app.js:7:58
    at require (WAService.js:1:1115197)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:17996/appservice/appservice?t=1561448578734:1427:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:17996/appservice/appservice?t=1561448578734:1439:20)

**Comment by Gcaufy** [comment]
可以给出报错的那一行的示例代码吗？

**Comment by nishino-tsukasa** [comment]
你的redux那个demo示例是不能运行的，也是这个原因。redux引入了lodash，lodash报这个错。

**Comment by Gcaufy** [comment]
redux lodash 的问题是之前修复过的，报错是 can not read Math of undeinfed 之类的。 升级最新版本的 cli 和 core 就可以了。
你的这个 Cannot read property 'prototype' of undefined  的问题我没有办法复现。如果你能点进去给我看具体报错的是哪一行就好了。

**Comment by nishino-tsukasa** [comment]
wepy init standard#2.0.x myproj
cd myproj
npm install @wepy/cli
npm install
npm run build
![image](https://user-images.githubusercontent.com/12985781/60391843-bb9bea80-9b2a-11e9-8d78-d2f6eee40015.png)
![image](https://user-images.githubusercontent.com/12985781/60391852-e9812f00-9b2a-11e9-9b5f-04b92ddd12bd.png)
![image](https://user-images.githubusercontent.com/12985781/60391860-087fc100-9b2b-11e9-9688-c9f5fcfdeab6.png)

**Comment by Gcaufy** [comment]
安装最新版本试试看呢？

**Comment by ChrisDowney1996** [comment]
> 安装最新版本试试看呢？

嗯，2.0.0-alpha.13版本可以了。
