### ISSUE TITLE
2.0.0-alpha.10 修改扩展名.vue <config> 引用组件失败

### ISSUE THREAD

**Issue by lich-yoo** [Tencent/wepy#2230]
## Description
  wepy 2.0.0-alpha.10，使用cli init 项目，在 `wepy.config.js` 中更改扩展名 `wpyExt: '.vue'` 后打包异常。
  报错日志为：

> [10:09:51] ERR! Error: Can't resolve '../components/list' in 'E:\platform-wepy\src\pages'
[10:09:51] ERR!     at doResolve (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:180:19)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn0 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn0 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
[10:09:51] ERR!     at resolver.doResolve (E:\platform-wepy\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn1 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:58:1)
[10:09:51] ERR!     at resolver.doResolve (E:\platform-wepy\node_modules\enhanced-resolve\lib\AliasFieldPlugin.js:47:37)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn0 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn0 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
[10:09:51] ERR!     at resolver.doResolve (E:\platform-wepy\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
[10:09:51] ERR!     at hook.callAsync (E:\platform-wepy\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[10:09:51] ERR!     at _fn4 (eval at create (E:\platform-wepy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)

关键日志：

> [10:09:51] ERR!   missing:
[10:09:51] ERR!    [ 'E:\\platform-wepy\\src\\components\\wepy-list.wpy',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.js',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.ts',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.json',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.node',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.wxs',
[10:09:51] ERR!      'E:\\platform-wepy\\src\\components\\wepy-list.wpy.vue' ] }

**注：这里应该找 components\\wepy-list.vue 而不是 components\\wepy-list.wpy.vue**

引用代码：

```xml
<config>
{
    navigationBarTitleText: 'WePY 2.0 Feature Demo',
    usingComponents: {
      panel: '~@/components/panel',
      counter: '~counter',
      list: '../components/list',
      group: '../components/group',
      "slide-view": "module:miniprogram-slide-view",
    }
}
</config>
```

## Environment
  * wepy-cli version:  2.0.0-alpha.10
  * wepy version: @wepy/core: 2.0.0-alpha.8
  * other version:  enhanced-resolve: 4.1.0

**Comment by Gcaufy** [comment]
这个是因为在 package.json 里面使用了 `aliasFields`， 里面的路径还是使用的 `.wpy` 后缀，修改一下即可。
