### ISSUE TITLE
$invoke  A组件调用B组件 方法 报错  和  props 传值

### ISSUE THREAD

**Issue by jimengchao** [Tencent/wepy#236]
同一文件夹下的 A组件 和 B组件

A组件  methods 方法中调用
```
methods = {
        addDish(parentIndex, index){
            this.$invoke('./B', 'addDish',index);
        }
}
```

错误 : Invalid path: null; 

props

父组件 向 子组件 用 props 传值 

```
// 父组件
<goods :store.sync="store" :mode.sync="mode"></goods>

// 子组件
<view>{{store}}{{mode}}<view> // 这里是正确的


props = {
    store: String,
    mode:String
}

async onLoad(){
  console.log(this.store)  // undefined
  console.log(this.mode)  // undefined
}
```

**Comment by coolhwm** [comment]
1.  `invoke`的第一个参数貌似是组件名称，我尝试这样是可以用的。
```
// 调用
this.$invoke('Tips', 'show', '提示信息');

// 定义
components = {
      Tips: FormTips
    };
```
2. `store` 和 `mode` 如果是异步数据的话，这个表现应该是正常的，视图`onLoad`的时候，父组件的异步数据还没加载完毕。如果数据源是父组件提供，那么应该也没必要在`onLoad`中获取吧。

**Comment by jimengchao** [comment]
@coolhwm  十分感谢！

**Comment by coolhwm** [comment]
@Gcaufy  文档中似乎写的是组件路径，我用这个也不行

```
$invoke $invoke是一个组件对另一个组件的直接调用，通过传入的组件路径找到相应组件，然后再调用其方法。 如果想在Page_Index中调用组件A的某个方法：

this.$invoke('ComA', 'someMethod', 'someArgs'); 
如果想在组件A中调用组件G的某个方法：

this.$invoke('./../ComB/ComG', 'someMethod', 'someArgs');
```

**Comment by Gcaufy** [comment]
@jimengchao 组件路径并非文件相对路径，比如page下有A,B 两个子组件，那A,B的相对路径就是一样的。如果A下面还有C，那么C访问B就是 `./../B`

**Comment by KingJeason** [comment]
这点有点坑,如果一个页面下有 a,b两个组件, 路径要写 '../a'  况且这个名字要写你在页面注册的那个名字,而不是文件的名字.

**Comment by KingJeason** [comment]
当然我说的在一个文件夹的情况.你可以看看$invoke的源码,里面有怎么寻找路径

**Comment by guozimo** [comment]
thirdScriptError
Invalid path: null;at pages/mycar page lifeCycleMethod onLoad function
Error: Invalid path: null
    at RecoverGoods.$invoke (http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:399:23)
    at RecoverGoods.onLoad (http://127.0.0.1:58817/appservice/components/recoverGoods/recoverGoods.js:62:12)
    at http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:230:56
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:229:49
    at Array.forEach (<anonymous>)
    at Myidle.$init (http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:225:22)
    at Myidle.$init (http://127.0.0.1:58817/appservice/npm/wepy/lib/page.js:60:104)
    at e.config.onLoad (http://127.0.0.1:58817/appservice/npm/wepy/lib/base.js:154:18)
    at e.<anonymous> (http://127.0.0.1:58817/appservice/__dev__/WAService.js:17:25368)


这是什么原因呢 求回答

**Comment by Windancer** [comment]
我也碰到这个问题了，求解答。

**Comment by shiran1992** [comment]
对于兄弟组件之间使用invoke，路径我还是有疑惑。现在又开始报这个错误。
Cannot read property '$com' of undefined;at pages/square/demo_page page $DemoA$doCom1 function
TypeError: Cannot read property '$com' of undefined
    at http://127.0.0.1:64524/appservice/npm/wepy/lib/component.js:386:38
    at Array.forEach (<anonymous>)
    at DemoA.$getComponent (http://127.0.0.1:64524/appservice/npm/wepy/lib/component.js:374:26)
    at DemoA.$invoke (http://127.0.0.1:64524/appservice/npm/wepy/lib/component.js:396:24)
    at DemoA.doCom1 (http://127.0.0.1:64524/appservice/components/demoa.js:36:14)
    at e.config.(anonymous function) (http://127.0.0.1:64524/appservice/npm/wepy/lib/base.js:90:29)
    at e.<anonymous> (http://127.0.0.1:64524/appservice/__dev__/WAService.js:18:4907)
    at e.a (http://127.0.0.1:64524/appservice/__dev__/WAService.js:17:31002)
    at z (http://127.0.0.1:64524/appservice/__dev__/WAService.js:17:24941)
    at Function.<anonymous> (http://127.0.0.1:64524/appservice/__dev__/WAService.js:17:26562)
