### ISSUE TITLE
编译报错 ERR! Cannot read property 'parsed' of null

### ISSUE THREAD

**Issue by duxin1992** [Tencent/wepy#2376]
项目写着写着突然就报这个错：
ERR! Cannot read property 'parsed' of null？？？
有大佬遇到过吗？

前天刚解决完ERR! Cannot read property 'update' of null？？？的报错，今天又来

**Comment by Gcaufy** [comment]
加上 --log trace 给我看看完整的错误栈

**Comment by DAIXK** [comment]
[12:39:28] info component building components
[12:39:28] ERR! TypeError: Cannot read property 'parsed' of null
[12:39:28] ERR!     at comps.forEach.comp (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:27:38)
[12:39:28] ERR!     at Array.forEach (<anonymous>)
[12:39:28] ERR!     at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:7:11)
[12:39:28] ERR!     at fns.forEach (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:41:20)
[12:39:28] ERR!     at Array.forEach (<anonymous>)
[12:39:28] ERR!     at Compile.hookSeq (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:35:9)
[12:39:28] ERR!     at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:267:12)
[12:39:28] ERR!     at Compile.buildComps (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:298:18)
[12:39:28] ERR!     at <anonymous>
[12:39:28] ERR!  { TypeError: Cannot read property 'parsed' of null
[12:39:28] ERR!     at comps.forEach.comp (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:27:38)
[12:39:28] ERR!     at Array.forEach (<anonymous>)
[12:39:28] ERR!     at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:7:11)
[12:39:28] ERR!     at fns.forEach (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:41:20)
[12:39:28] ERR!     at Array.forEach (<anonymous>)
[12:39:28] ERR!     at Compile.hookSeq (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:35:9)
[12:39:28] ERR!     at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:267:12)
[12:39:28] ERR!     at Compile.buildComps (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:298:18)
[12:39:28] ERR!     at <anonymous>
[12:39:28] ERR!   stack: 'TypeError: Cannot read property \'parsed\' of null\n    at comps.forEach.comp (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:27:38)\n    at Array.forEach (<anonymous>)\n    at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/plugins/build/components.js:7:11)\n    at fns.forEach (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:41:20)\n    at Array.forEach (<anonymous>)\n    at Compile.hookSeq (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/hook.js:35:9)\n    at Compile.buildComponents (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:267:12)\n    at Compile.buildComps (/Volumes/TOSHIBA/work/jinan/node_modules/_@wepy_cli@2.0.0-alpha.25@@wepy/cli/core/compile.js:298:18)\n    at <anonymous>' }
[12:39:28] ERR! compile Compile failed.
[12:39:28] info watching...

**Comment by tiancantudousi** [comment]
我初始化项目启动时也碰到了，怎么解决的呀

**Comment by Gcaufy** [comment]
@tiancantudousi  可以发完整执行命令看看吗？

**Comment by Gcaufy** [comment]
@tiancantudousi 刚再次测试了一下 empty 和 standard 模板，都是可以编译通过的。

```
 $ wepy -v
2.0.0-alpha.28
```

**Comment by tiancantudousi** [comment]
好像是我组件的问题，组件文件里没有任何代码，后来删掉重新写就正常了，多谢帮忙看问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gcaufy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月24日(星期天) 下午5:37
收件人:&nbsp;"Tencent/wepy"<wepy@noreply.github.com&gt;;
抄送:&nbsp;"米影"<1329972027@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/wepy] 编译报错 ERR! Cannot read property 'parsed' of null (#2376)





 
@tiancantudousi 刚再次测试了一下 empty 和 standard 模板，都是可以编译通过的。
  $ wepy -v 2.0.0-alpha.28

**Comment by xswby** [comment]
新建一个项目后，加个tabbar，增加一些图标，编译出现的问题
