### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by superlbr** [Tencent/wepy#2380]
引入一个原生的组件，修改其中的js文件，就会报错
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'file' of undefined
    at Compile.<anonymous> (/small2/node_modules/@wepy/cli/core/plugins/parser/file.js:17:27)
    at Compile.hookUnique (/small2/node_modules/@wepy/cli/core/hook.js:54:21)
```

**Comment by dlhandsome** [comment]
已知问题，下一个版本修复
