### ISSUE TITLE
在store设置getters后会报错

### ISSUE THREAD

**Issue by MaZchao** [Tencent/wepy#2411]
## Description

新建项目，`npm run dev`后在`src/store/index.js`文件中增加getters字段，如下：
```javascript
export default new Vuex.Store({
  state: {
    counter: 0
  },
  //  新增getters
  getters: {
    counter: state => state.counter
  },
  // ....
})
```
增加getters之后重新编译，开发者工具会报错如下：
```error
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'push' of undefined 
 TypeError: Cannot read property 'push' of undefined
    at new Watcher (http://127.0.0.1:52202/appservice/vendor.js:1423:16)
    at http://127.0.0.1:52202/appservice/vendor.js:1770:21
    at Array.forEach (<anonymous>)
    at initComputed (http://127.0.0.1:52202/appservice/vendor.js:1761:25)
    at new WepyConstructor (http://127.0.0.1:52202/appservice/vendor.js:1799:5)
    at resetStoreVM (http://127.0.0.1:52202/appservice/vendor.js:4042:15)
    at new Store (http://127.0.0.1:52202/appservice/vendor.js:3817:3)
    at http://127.0.0.1:52202/appservice/store/index.js:12:16
    at require (WAService.js:1:1439605)
    at WAService.js:1:1439215
```

## Environment

  * Platform: 开发者工具
  * Platform version: v1.02.1905151
  * Wechat version: 2.8.3
  * wepy-cli version: 2.0.0-alpha.19
  * wepy version: 2.0.0-alpha.9
  * other version: "@wepy/x": "2.0.2"
  
## Reproduce

 如描述

### Expected Results

可以正常使用vuex的getters

谢谢。

**Comment by zhanggongze** [comment]
这个问题 解决了嘛？

**Comment by quany** [comment]
我也是同样的问题

**Comment by quany** [comment]
看了 vuex 源码，会去实例化一个 vue

**Comment by Luobro** [comment]
同样的问题

**Comment by cielu** [comment]
那么久的问题了，还没解决。。感觉当初选这个框架选错了

**Comment by chenillen** [comment]
還是沒解決嘛？還以為是 getters 寫的有問題

**Comment by cielu** [comment]
可以不用 getters ，直接用 mapState ，如下代码可正常使用
```
  computed: {
    ...mapState({
      cartGoodsNum: function(state) {
        if (this.storeInfo !== null && typeof state.shoppingCart[this.storeInfo.storeId] !== 'undefined') {
          return state.shoppingCart[this.storeInfo.storeId]['goodsNum']
        }
        return {}
      },
      goodsTotalNum: function (state) {
        if (this.storeInfo !== null && typeof state.shoppingCart[this.storeInfo.storeId] !== 'undefined') {
          return state.shoppingCart[this.storeInfo.storeId]['totalNum']
        }
      }
    })
  }
```

**Comment by Gcaufy** [comment]
更新版本试试：
```
npm install @wepy/core@next --save
```

**Comment by chenillen** [comment]
> 可以不用 getters ，直接用 mapState ，如下代码可正常使用
> 
> ```
>   computed: {
>     ...mapState({
>       cartGoodsNum: function(state) {
>         if (this.storeInfo !== null && typeof state.shoppingCart[this.storeInfo.storeId] !== 'undefined') {
>           return state.shoppingCart[this.storeInfo.storeId]['goodsNum']
>         }
>         return {}
>       },
>       goodsTotalNum: function (state) {
>         if (this.storeInfo !== null && typeof state.shoppingCart[this.storeInfo.storeId] !== 'undefined') {
>           return state.shoppingCart[this.storeInfo.storeId]['totalNum']
>         }
>         return 0
>       }
>     })
>   }
> ```

確實可以，但是沒有 getters 也有點奇怪。好在 @Gcaufy 已經fix了

**Comment by chenillen** [comment]
> 更新版本试试：
> 
> ```
> npm install @wepy/core@next --save
> ```

可以了！
