### ISSUE TITLE
编译报错ERR! Source and destination must not be the same.

### ISSUE THREAD

**Issue by Colin-XKL** [Tencent/wepy#2556]
## Description

wepy每次编译时都会报错
```ERR! Source and destination must not be the same.```
即便是刚刚创建的新项目，也只有第一次编译可以通过，后面就算没有修改文件也会报这个错误。
初步测试了一下，是因为上一次的编译产物的问题。网上有类似问题的是因为文件夹权限，但是我这边的项目是放在FAT32分区上，不存在文件权限问题。
希望开发者可以解决下这个问题，不然dev模式监听文件变化实时编译根本没法用啊

## Environment

  * Platform: 开发者工具实时预览，VSCode编辑
  * Platform version: [对应工具或者iOS或者Andriod的版本号]none
  * Wechat version: [微信版本号]none
  * wepy-cli version: 2.0.0-alpha.26
  * other version: 
```js
"dependencies": {
    "@wepy/x": "^2.0.2",
    "@wepy/core": "^2.0.0-alpha.9",
    "miniprogram-slide-view": "0.0.3"
  }
```
## Reproduce

新建一个项目，进行编译。第二次及以后的编译都会报错，清理上一次的编译产物后重新编译才能通过。

**Comment by Colin-XKL** [comment]
补充信息：
1. 之前wepy 1.x的版本使用正常
2. 问题复现于FAT32分区上的项目文件，在APFS分区上未复现
3. 测试平台 Mac OS X 10.14.2

**Comment by Colin-XKL** [comment]
补充信息：
4. 部分错误输出信息
```
[20:50:43] ERR! Error: Source and destination must not be the same.
[20:50:43] ERR!     at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:80:17
[20:50:43] ERR!     at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:38:16
[20:50:43] ERR!     at callback (/usr/local/lib/node_modules/@wepy/cli/node_modules/graceful-fs/polyfills.js:295:20)
[20:50:43] ERR!     at FSReqCallback.oncomplete (fs.js:172:5)
[20:50:43] ERR!  Error: Source and destination must not be the same.
[20:50:43] ERR!     at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:80:17
[20:50:43] ERR!     at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:38:16
[20:50:43] ERR!     at callback (/usr/local/lib/node_modules/@wepy/cli/node_modules/graceful-fs/polyfills.js:295:20)
[20:50:43] ERR!     at FSReqCallback.oncomplete (fs.js:172:5) {
[20:50:43] ERR!   stack: 'Error: Source and destination must not be the same.\n' +
[20:50:43] ERR!     '    at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:80:17\n' +
[20:50:43] ERR!     '    at /usr/local/lib/node_modules/@wepy/cli/node_modules/fs-extra/lib/util/stat.js:38:16\n' +
[20:50:43] ERR!     '    at callback (/usr/local/lib/node_modules/@wepy/cli/node_modules/graceful-fs/polyfills.js:295:20)\n' +
[20:50:43] ERR!     '    at FSReqCallback.oncomplete (fs.js:172:5)'
[20:50:43] ERR! }
[20:50:43] ERR! compile Compile failed.
```

**Comment by Gcaufy** [comment]
与代码和项目有关吗？是所有项目都不能编译还是只有某个特定项目？

**Comment by Colin-XKL** [comment]
使用wepy 的standard初始化的项目，即便我一行代码都没有改，也会出现这个错误。
目前来看，至少wepy 的standard的模板会出现这个问题，很容易复现。稍后我再测试一下空模板项目

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/78889380-2143dc80-7a96-11ea-92ae-7949c2673654.png)

我这里无法复现

**Comment by Colin-XKL** [comment]
我这边测试的完整复现流程是这样的：
1. 在FAT32的磁盘分区上新建一个文件夹，cd进入
2. `wepy init standard testproject`
3. 配置不修改，使用默认
4. 进入项目文件夹，`npm install`安装依赖
5. `wepy build`进行编译，第一次编译没有问题
6. 不对项目文件做任何修改，再次执行`wepy build`就会报错。
其中`wepy build`即便更换为`npm run build`也是一样的结果，我本地测试过多次。
