### ISSUE TITLE
Cannot read property 'parsed' of null 同时static文件好像没有打包到weapp下

### ISSUE THREAD

**Issue by xswby** [Tencent/wepy#2736]
提交ISSUE前请确保已认真阅读以下内容

*Please read the following information carefully before you open an issue.*

在提交issue之前必须确认以下问题：

*Please make sure you understand the following points:*

* 必须是一个bug或者功能新增。

* *It must be a bug or a feature request*

* 必须是WePY相关问题，原生小程序问题去[开发者论坛](https://developers.weixin.qq.com/)。

* *It must be a WePY issue.*

* 已经在issue中搜索过，并且没有找到相似的issue或者解决方案。

* *I searched issue already but I didn't find any relevant issues or solutions.*

* 完善下面模板中的信息

* *Please fill out the following template*

阅读完后请在提交的issue中删除以上内容，包括分割线

DELETE THE INFORMATION ABOVE(INCLUDE THE SEPARATION LINE) BEFORE YOU OPEN AN ISSUE

------------------------
## Description

Cannot read property 'parsed' of null

## Environment

  * Platform: [iOS]
  * Platform version: [mac 10.15.7]
  * Wechat version: [2.16.0]
  * wepy-cli version: [v2.1.0]
  * wepy version: [v2.1.0]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

新建一个标准的项目
在app.wpy <config> 里pages 添加wpy文件编辑出错，添加tabbar后可复现上面的问题
### Observed Results

无法编译通过
  
### Expected Results

  [期望表现]
  编译通过
  

## Relevant Code / Logs
TypeError: Cannot read property 'parsed' of null
[22:20:24] ERR!     at comps.forEach.comp (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/plugins/build/components.js:27:38)
[22:20:24] ERR!     at Array.forEach (<anonymous>)
[22:20:24] ERR!     at Compile.buildComponents (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/plugins/build/components.js:7:11)
[22:20:24] ERR!     at fns.forEach (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/hook.js:41:20)
[22:20:24] ERR!     at Array.forEach (<anonymous>)
[22:20:24] ERR!     at Compile.hookSeq (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/hook.js:35:9)
[22:20:24] ERR!     at Compile.buildComponents (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/compile.js:297:12)
[22:20:24] ERR!     at Compile.buildComps (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/compile.js:328:18)
[22:20:24] ERR!  { TypeError: Cannot read property 'parsed' of null
[22:20:24] ERR!     at comps.forEach.comp (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/plugins/build/components.js:27:38)
[22:20:24] ERR!     at Array.forEach (<anonymous>)
[22:20:24] ERR!     at Compile.buildComponents (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/plugins/build/components.js:7:11)
[22:20:24] ERR!     at fns.forEach (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/hook.js:41:20)
[22:20:24] ERR!     at Array.forEach (<anonymous>)
[22:20:24] ERR!     at Compile.hookSeq (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/hook.js:35:9)
[22:20:24] ERR!     at Compile.buildComponents (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/compile.js:297:12)
[22:20:24] ERR!     at Compile.buildComps (/Users/xusen/.nvm/versions/node/v10.14.0/lib/node_modules/@wepy/cli/core/compile.js:328:18)
[22:20:24] ERR!   stack:

**Comment by xswby** [comment]
补充上面的问题
"dependencies": {
    "@wepy/x": "^2.1.0",
    "@wepy/core": "^2.0.0-alpha.16",
    "miniprogram-slide-view": "0.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@wepy/babel-plugin-import-regenerator": "0.0.2",
    "@wepy/cli": "^2.0.0-alpha.28",
    "@wepy/compiler-babel": "^2.0.1",
    "@wepy/compiler-less": "^2.0.1",
    "babel-eslint": "^7.2.1",
    "cross-env": "^5.1.3",
    "less": "^3.8.1",
    "vue": "^2.6.12"
  }

**Comment by thelen** [comment]
我也遇到了这个问题，楼主解决了吗
