### ISSUE TITLE
mac 本报错 compiler is not a function

### ISSUE THREAD

**Issue by Bruce12** [Tencent/wepy#401]
`ymtdeMacBook-Air-4:myproject ymt$ wepy build
[18:10:39] [编译] 入口: src/app.wpy
/usr/local/lib/node_modules/wepy-cli/lib/eslint.js:17
        compiler(esConfig, filepath);
        ^

TypeError: compiler is not a function
    at exports.default (/usr/local/lib/node_modules/wepy-cli/lib/eslint.js:17:9)
    at Object.lint (/usr/local/lib/node_modules/wepy-cli/lib/compile-wpy.js:350:30)
    at Object.compile (/usr/local/lib/node_modules/wepy-cli/lib/compile-wpy.js:376:18)
    at Object.compile (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:337:38)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile.js:315:47
    at Array.forEach (<anonymous>)
    at Object.build (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:309:19)
    at Command.<anonymous> (/usr/local/lib/node_modules/wepy-cli/lib/wepy.js:245:27)
    at Command.listener (/usr/local/lib/node_modules/wepy-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
ymtdeMacBook-Air-4:myproject ymt$
`
按照官方文档，配置环境，弄了很久也没解决，删除包，重新下载也不行，环境重新配置也不行！

**Comment by Gcaufy** [comment]
```
npm i wepy-eslint --save-dev
```

**Comment by Gcaufy** [comment]
这里可以了么？这里之前忽略了异常处理，不过已修复了，还没发布
