### ISSUE TITLE
wepy build --output ant 报错wepy 版本 v1.5.9-4

### ISSUE THREAD

**Issue by mosade** [Tencent/wepy#437]
```
  wepy build --output ant
D:\nodejs\node_modules\wepy-cli\lib\compile.js:254
            dist = wepyrc.ant.dist || dist || 'ant';
                                      ^

ReferenceError: dist is not defined
    at Object.init (D:\nodejs\node_modules\wepy-cli\lib\compile.js:254:39)
    at Command.<anonymous> (D:\nodejs\node_modules\wepy-cli\lib\wepy.js:242:27)
    at Command.listener (D:\nodejs\node_modules\wepy-cli\node_modules\_commander@2.11.0@commander\index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (D:\nodejs\node_modules\wepy-cli\node_modules\_commander@2.11.0@commander\index.js:635:12)
    at Command.parse (D:\nodejs\node_modules\wepy-cli\node_modules\_commander@2.11.0@commander\index.js:457:21)
    at Object.<anonymous> (D:\nodejs\node_modules\wepy-cli\lib\wepy.js:255:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Comment by Gcaufy** [comment]
```
npm i wepy-cli@1.5.9-5 -g
```

**Comment by Gcaufy** [comment]
抱歉，中间的一次改动改出了点问题，已加入CI测试流程。

**Comment by mosade** [comment]
更新1.5.9-5后wepy build --output ant没问题,但是编译完成的支付宝小程序报错:
```
Error in (undefined) ./npm/wepy-async-function/index.js
Module build failed: TypeError: Cannot read property 'length' of null
 @ ./app.js 51:0-45
 @ ./.tea/entryFiles-development/index$.worker.js
```
发现在npm-->wepy-async-function 下的两个js文件都没有内容

**Comment by Gcaufy** [comment]
那你把这个import给拿掉试试？
