### ISSUE TITLE
如果发生过一次解析错误，下一次wepy build --watch的时候一直会有问题

### ISSUE THREAD

**Issue by lyh2668** [Tencent/wepy#501]
情景：
如果未定义components直接使用，则会报一个解析错误，比如：
```
[Error] 解析components出错，报错信息：ReferenceError: OrderTab is not defined
var wepy = "wepy";
var OrderList = "../order/list";
var OrderListItem = "../order/listItem";
return {
    'order-tab': OrderTab,
    'order-list': OrderList,
    'order-list-item': OrderListItem
  }
```
之后再执行wepy build --watch
将会出现以下错误：
```
C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:132
                    if (wpy[t]) {
                            ^

TypeError: Cannot read property 'script' of null
    at C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:132:29
    at Array.forEach (<anonymous>)
    at C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:131:49
    at Array.forEach (<anonymous>)
    at Object.findReference (C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:124:19)
    at C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:361:40
    at Array.forEach (<anonymous>)
    at Object.build (C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\compile.js:356:19)
    at Command.<anonymous> (C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\lib\wepy.js:243:27)
    at Command.listener (C:\Users\lenovo\AppData\Roaming\nvm\v8.6.0\node_modules\wepy-cli\node_modules\commander\index.js:300:8)
```
这个问题已经碰到两次了，而且爆了这个错误以后我尝试了很多方式都不能正常启动wepy build --watch，然后我只能重新git pull我之前的版本去解决。

**Comment by hojas** [comment]
我也遇到了这个问题，然后下载了最新版 wepy 和最新版微信开发者工具，最新版的编译不会出错，但是运行时报错了：
![image](https://user-images.githubusercontent.com/4729039/32597917-277b668e-c573-11e7-9e82-7143d4cd643e.png)

**Comment by lyh2668** [comment]
@hojas 我已经找到了错误的诱因，是由于建立了新的wpy文件，却没有添加template、script导致的，不过还是觉得这样非常不友好

**Comment by Gcaufy** [comment]
@lyh2668 给我具体还原步骤，我去优化一下

**Comment by lyh2668** [comment]
@Gcaufy 新建一个空白的.wpy文件，然后wepy build --watch就会报这个错了
主要是这个问题很难定位，其实应该只要添加对空白.wpy文件的判断应该就可以了

**Comment by ohYobbo** [comment]
这个问题确实坑啊   我还升级wepy框架   依赖删了一边又一边   最后才发现是这个问题    作者有时间填一下这个坑   这问题很难发现

**Comment by Gcaufy** [comment]
应该是已修复问题，参考这里：#538
