### ISSUE TITLE
针对组件局部样式scoped不起作用，有什么好的解决办法

### ISSUE THREAD

**Issue by 1162257086** [Tencent/wepy#527]
不然子组件可能无意中就会被父组件中的样式所干扰

**Comment by Gcaufy** [comment]
这个功能是测试过的，怎么会有问题呢？具体是什么问题

**Comment by 1162257086** [comment]
我用wepy-cli 1.6.0版本新建工程，利用你的wepy.config.js默认配置的话，在.wpy文件里
<style lang="less" scoped>....<style>这样的话，发现样式完全不被加载，如果想样式只有在当前组件有效的话，请问该怎么写入呢

**Comment by songyazhao** [comment]
我也遇到了同样的问题 组件的style设置了scoped 样式不会生效
```json
  "dependencies": {
    "axios": "^0.17.1",
    "wepy": "^1.6.0",
    "wepy-async-function": "^1.4.4",
    "wepy-com-toast": "^1.0.2"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "cross-env": "^5.1.1",
    "eslint": "^3.18.0",
    "eslint-config-standard": "^7.1.0",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-plugin-html": "^2.0.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^2.0.1",
    "wepy-compiler-babel": "^1.5.1",
    "wepy-compiler-pug": "^1.4.6",
    "wepy-compiler-stylus": "^1.3.10",
    "wepy-compiler-less": "^1.3.10",
    "wepy-eslint": "^1.5.3",
    "wepy-plugin-axios": "^0.1.7",
    "wepy-plugin-imagemin": "^1.5.2",
    "wepy-plugin-uglifyjs": "^1.3.6"
  }
```
```html
<style lang="stylus" scoped>
.cell
  height 60px
  display flex
  justify-content space-between
</style>

<template lang="pug">
  view(class='cell')
    text {{ label }}
    text {{ value }}
</template>

<script>
import wepy from 'wepy'

export default class Cell extends wepy.component {
  props = {
    label: {
      type: String,
      default: ''
    },
    value: {
      twoWay: true,
      type: String,
      default: ''
    }
  }
}
</script>
```
![image](https://user-images.githubusercontent.com/23444330/33112802-00d6b23c-cf90-11e7-83c9-7d6c6c51a5a7.png)

**Comment by Gcaufy** [comment]
参考一下看是不是这个问题

**Comment by songyazhao** [comment]
可以, 我在node_modules\wepy-cli\lib\compile-wpy.js中添加了如下代码,解决了该问题
```javascript
  filepath = _path2.default.resolve(filepath); // to fixed windows path bug
```
但是现在又有一个新的问题,我在一个组件中(x-popup)引入了另一个组件(x-mask),在x-mask中对style设置了scoped, 然后是没问题的,但是我在x-popup中对style也设置了scoped之后, 报错如下
```dos
PS E:\xampp\www\Caryu_Xiche> yarn build --watch
yarn build v1.0.2
$ cross-env NODE_ENV=production wepy build --no-cache "--watch"
[警告] 为了能够让 wepy 成功编译 axios, 已修改 axios 源文件
[警告] 你将只能配合 wepy-plugin-axios 在 wepy 中使用此项目中的 axios
C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile-wpy.js:67
                    _util2.default.error('ERROR IN : ' + _path2.default.relative(_util2.default.currentDir, _path2.default.join(opath.dir, opath.base)) + '\n' + x);
                                                                                                                                     ^

TypeError: Cannot read property 'dir' of undefined
    at error (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile-wpy.js:67:134)
    at Object.errorHandler.(anonymous function) [as error] (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\xmldom\dom-parser.js:48:4)
    at parse (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\xmldom\sax.js:190:17)
    at XMLReader.parse (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\xmldom\sax.js:30:3)
    at DOMParser.parseFromString (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\xmldom\dom-parser.js:26:7)
    at Object.resolveWpy (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile-wpy.js:362:44)
    at C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile.js:128:48
    at Array.forEach (<anonymous>)
    at Object.findReference (C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile.js:124:19)
    at C:\Users\Zero\AppData\Local\Yarn\config\global\node_modules\wepy-cli\lib\compile.js:361:40
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

###  ***x-popup.wpy***
```html
<style lang="stylus" scoped>
.x-popup
  position fixed
  left 0
  right 0
  bottom 0
  z-index 1001
  background-color transparent
  .x-popup__title
    font-size 30rpx
    line-height 30rpx
    padding 40rpx 30rpx
  .x-popup__content
    margin 0 75rpx
</style>

<template lang="pug">
  view(class='x-popup', style='background: {{ background }}', wx:if='{{ visible }}')
    view(class='x-popup__title') {{ title }}
    view(class='x-popup__content')
      slot(name='content')
    button(type='cancel', @tap='closePopupTap') 取消
  XMask(:visible.sync='visible', @tap.user="closePopupTap")
</template>

<script>
import wepy from 'wepy'
import XMask from './x-mask'

export default class XPopup extends wepy.component {
  components = {
    XMask
  }

  props = {
    visible: {
      type: Boolean,
      defult: false,
      twoWay: true
    },
    title: {
      type: String,
      default: ''
    },
    background: {
      type: String,
      default: 'white'
    }
  }

  methods = {
    closePopupTap() {
      this.visible = false
    }
  }
}
</script>

```

### ***x-mask.wpy***
```javascript
<style lang="stylus" scoped>
.x-mask
  position fixed
  left 0
  right 0
  top 0
  bottom 0
  z-index 1000
  background-color rgba(0, 0, 0, .65)
</style>

<template lang="pug">
  view(class='x-mask', wx:if='{{ visible }}', @tap='tapHandler')
</template>

<script>
import wepy from 'wepy'

export default class XMask extends wepy.component {
  props = {
    visible: {
      type: Boolean,
      defult: false,
      twoWay: true
    }
  }

  methods = {
    tapHandler() {
      this.$emit('tap')
    }
  }
}
</script>
```

**最后谢谢您在百忙中回答我的问题**

**Comment by Gcaufy** [comment]
这个从代码上看，应该是你的wxml编译报错的。

**Comment by songyazhao** [comment]
一切都是在x-popup组件上style加入scoped之后发生的, 去掉的话一点事没有,
现在找到了影响它的关键地方 **":show.sync='visible'**
```html
  XMask(:show.sync='visible', @tap.user="closePopupTap")
```

我在 **compile-wpy.js** 添加了如下
![fixed xml compile error](https://github.com/wepyjs/wepy/commit/559f910f3a8267f10cc0f4fd11e3d4bf0f8d6ca8)

***然后现在报错如下:***
```node
[11:51:19] [编译] 组件: src\components\x-popup.wpy
[Error] ERROR IN : src\components\x-popup.wpy
[xmldom error]  element parse error: Error: invalid attribute::show.sync
@#[line:undefined,col:undefined]
[Error] ERROR IN : src\components\x-popup.wpy
[xmldom error]  element parse error: Error: invalid attribute::show.sync
@#[line:undefined,col:undefined]
[Error] ERROR IN : src\components\x-popup.wpy
[xmldom error]  element parse error: Error: invalid attribute::show.sync
@#[line:undefined,col:undefined]
```

**Comment by Gcaufy** [comment]
如果改写成wxml的形式呢？看看是不是PUG的原因 。

**Comment by Gcaufy** [comment]
这是另外一个问题吧，再开一个ISSUE

**Comment by shengbeiniao** [comment]
我也遇到同样的问题，在组件的wpy文件中引用
```
<style lang="less" src="./DiscountRule.less" scoped></style>
```
编译后的wxml文件，未引用样式

**Comment by Gcaufy** [comment]
@shengbeiniao 升级成1.7.1试下
