### ISSUE TITLE
自定义组件引入，老是报path错误

### ISSUE THREAD

**Issue by winglau14** [Tencent/wepy#532]
thirdScriptError
Invalid path: undefined;at pages/corpIndex/corpIndex page openItem function
Error: Invalid path: undefined

**Comment by zaxlct** [comment]
你的路径写的不对，和 wepy 没有关系。
usingComponents 里的路径最前面加上斜杠试试

**Comment by harrydengchao** [comment]
我也遇到了这个问题，不清楚原因是什么。官方文档写的是在页面内调用，直接传入组件名就可以。但是我这里很奇怪。有的组件能调用成功，有的失败。莫名其妙。
![image](https://user-images.githubusercontent.com/13941171/34637753-d2b1e3c8-f2f7-11e7-9987-89c211666377.png)

**Comment by guozimo** [comment]
我也想知道这个问题的答案

**Comment by guozimo** [comment]
WAService.js:3 thirdScriptError
Invalid path: null;at pages/mycar page lifeCycleMethod onLoad function
Error: Invalid path: null
    at RecoverGoods.$invoke (http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:399:23)
    at RecoverGoods.onLoad (http://127.0.0.1:58817/appservice/components/recoverGoods/recoverGoods.js:62:12)
    at http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:230:56
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:229:49
    at Array.forEach (<anonymous>)
    at Myidle.$init (http://127.0.0.1:58817/appservice/npm/wepy/lib/component.js:225:22)
    at Myidle.$init (http://127.0.0.1:58817/appservice/npm/wepy/lib/page.js:60:104)
    at e.config.onLoad (http://127.0.0.1:58817/appservice/npm/wepy/lib/base.js:154:18)
    at e.<anonymous> (http://127.0.0.1:58817/appservice/__dev__/WAService.js:17:25368)

**Comment by guozimo** [comment]
上面的报错有人知道怎么解么

**Comment by uewill** [comment]
遇到相同的问题，有知道的么？
