### ISSUE TITLE
component 层级到达3层时点击事件报错

### ISSUE THREAD

**Issue by LewisLZ** [Tencent/wepy#649]
这是错误日志

> Cannot read property '1' of undefined;at pages/index page $goods$mainReco$seckillItem$openSeckill1 function
TypeError: Cannot read property '1' of undefined
    at http://127.0.0.1:9973/appservice/npm/wepy/lib/component.js:331:56
    at SeckillItem.$setIndex (http://127.0.0.1:9973/appservice/npm/wepy/lib/component.js:343:35)
    at e.config.(anonymous function) (http://127.0.0.1:9973/appservice/npm/wepy/lib/base.js:81:28)
    at e.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:891)
    at e.a (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:27775)
    at G (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:22293)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:23882)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:29278
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:6:7284
    at e.(anonymous function) (http://127.0.0.1:9973/appservice/__dev__/WAService.js:3:31625)

**Comment by LewisLZ** [comment]
作者可以回复一下 这个问题吗？ 什么原因导致的呢？

**Comment by Gcaufy** [comment]
有没有使用repeat？

**Comment by LewisLZ** [comment]
都是使用的 repeat
