### ISSUE TITLE
如何修改三方库并使用？有非必要文件的copy与编译导致报错

### ISSUE THREAD

**Issue by NoraGithub** [Tencent/wepy#762]
当需要修改三方库的代码时，我将`git clone`整个库下来，修改后重新引入。
```
import F2 from './miniapp-f2/index.js'
...
```
但却导致整个目录下的文件都被复制进来，这是否有必要？
```
[22:45:02] [拷贝] EDITORCONFIG: src/components/datafile/miniapp-f2/.editorconfig
[22:45:02] [拷贝] ESLINTIGNORE: src/components/datafile/miniapp-f2/.eslintignore
[22:45:02] [拷贝] ESLINTRC: src/components/datafile/miniapp-f2/.eslintrc
[22:45:02] [拷贝] GIT : src/components/datafile/miniapp-f2/.git
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/.github/ISSUE_TEMPLATE.md
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/.github/PULL_REQUEST_TEMPLATE.md
[22:45:02] [拷贝] GITIGNORE: src/components/datafile/miniapp-f2/.gitignore
[22:45:02] [拷贝] YML : src/components/datafile/miniapp-f2/.travis.yml
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/CHANGELOG.md
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/CONTRIBUTING.md
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/CONTRIBUTING.zh-CN.md
[22:45:02] [拷贝] TECH/WEPY-F2/SRC/COMPONENTS/DATAFILE/MINIAPP-F2/LICENSE: src/components/datafile/miniapp-f2/LICENSE
[22:45:02] [拷贝] MD  : src/components/datafile/miniapp-f2/README.md
[22:45:02] [拷贝] CSS : src/components/datafile/miniapp-f2/demos/assets/bootstrap-4.0.0-beta/bootstrap-grid.min.css
[22:45:02] [拷贝] CSS : src/components/datafile/miniapp-f2/demos/assets/bootstrap-4.0.0-beta/bootstrap.min.css
[22:45:03] [拷贝] CSS : src/components/datafile/miniapp-f2/demos/assets/codemirror-5.29.0/codemirror-merged.min.css
[22:45:14] [拷贝] CSS : src/components/datafile/miniapp-f2/demos/assets/common.css
[22:45:30] [拷贝] CSS : src/components/datafile/miniapp-f2/demos/assets/index.css
[22:45:36] [拷贝] NJK : src/components/datafile/miniapp-f2/demos/index.njk
[22:45:36] [拷贝] JSON: src/components/datafile/miniapp-f2/package.json
```
而且这时`test/*`或`demo/*`下依赖的库也将报错，按道理不会影响index文件的编译
```
[Error] Error: 找不到模块: chai
被依赖于: /Users/NoraChan/Desktop/geekhacker.tech/wepy-f2/src/components/datafile/f2/test/unit/attr/color-util-spec.js。
请尝试手动执行 npm install chai 进行安装。
    at /Users/NoraChan/.nave/installed/miniapp/lib/node_modules/wepy-cli/lib/compile-script.js:79:31
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.resolveDeps (/Users/NoraChan/.nave/installed/miniapp/lib/node_modules/wepy-cli/lib/compile-script.js:49:21)
    at /Users/NoraChan/.nave/installed/miniapp/lib/node_modules/wepy-cli/lib/compile-script.js:218:27
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

以上问题是否我理解错误或者使用方法有问题呢？如果没有，是不是应该按照提示，每一个都安装？万一不同的三方库有版本冲突该如何解决？

**Comment by NoraGithub** [comment]
```
import cloneDeep from 'lodash/cloneDeep'
```
也是失败的。
已经 `npm install lodash -S`了

**Comment by Gcaufy** [comment]
对于src文件夹中的文件都会进行编译拷贝
如果是简单改动的话，建议还是用npm安装，然后编译时使用replace插件修改代码。
如果改动比较多的话，可以试试使用 .wepyignore文件，可以排除掉不想编译的文件

**Comment by NoraGithub** [comment]
改动不算多，但可预见可能改动会比较多，所以选择这个方案，而且方便track。
目前解决了。使用的`编辑.wepyignore文件`方案

主要是引发了以下的思考：
1. `简单改动建议还是用 npm 安装`是如何实现呢？建立私人 regitry 吗？不太理解
2. 如果同时使用两个三方的库，而且同时需要修改，却存在依赖的版本冲突，如何解决？（是不是用npm install 方案可以解决？）
3.wepy 的build 似乎不是 webpack 那套，没有import 的情况下也会编译，是否可以或者说有必要改善呢？（我的理解是，webpack是 import 才编译）

**Comment by Gcaufy** [comment]
1. npm 安装后通过replace插件修改包内容
2. 包都修改了还管什么版本呢
3. 那是针对node_modules的内容的，非import的不会编译，但对于src内的内容，会全部copy。因为webpack是可以打包成一个文件，但是wepy并非是要打包的一个文件。

**Comment by songguangyu** [comment]
能不能搞个配置 让某些目录不拷贝，比如图片上CDN了 图片目录就没必要拷贝了
