### ISSUE TITLE
不支持 "transform-runtime" 插件。

### ISSUE THREAD

**Issue by Samlv9** [Tencent/wepy#799]
```
module.exports = {
    "target": configs.directories.bin, // 预计新版本的写法。
    "output": configs.directories.bin, // 老版本的写法。
    "compilers": {
        "babel": {
            "presets": ["env"],
            "plugins": [
                ["transform-runtime", { "helpers": true, "polyfill": false, "regenerator": false }],
                "transform-class-properties", 
                "transform-decorators-legacy", 
                "transform-object-rest-spread", 
                "transform-export-extensions"
            ]
        },
        "sass": {
            "indentWidth": 4,
            "outputStyle": (development ? "expanded" : "compressed")
        }
    },
    "plugins": (development ? defaultPlugins : Object.assign(defaultPlugins, minifyPlugins))
};
```

上面是我的配置文件，但是报错了：
```
[Error] TypeError: Cannot read property 'modulePath' of null
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:95:47
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:49:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:218:27
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by Gcaufy** [comment]
使用你的config 编译成功了

![image](https://user-images.githubusercontent.com/2182004/35138341-05b12b0e-fd29-11e7-809b-392a3322f821.png)

可能是alpha4版本中解决的一个问题。建议你升级 alpha4 版本测试一下看看

```
npm i wepy-cli@1.6.1-alpha4 --g
```

**Comment by Samlv9** [comment]
@Gcaufy 太感谢了～～我周一试试～

**Comment by uniwisi** [comment]
> 使用你的config 编译成功了
> 
> ![image](https://user-images.githubusercontent.com/2182004/35138341-05b12b0e-fd29-11e7-809b-392a3322f821.png)
> 
> 可能是alpha4版本中解决的一个问题。建议你升级 alpha4 版本测试一下看看
> 
> ```
> npm i wepy-cli@1.6.1-alpha4 --g
> ```

it's very helpful to me
