### ISSUE TITLE
wepy-plugin-filemin 报错问题

### ISSUE THREAD

**Issue by coolhwm** [Tencent/wepy#899]
版本：wepy@1.6.1-alpha3， wepy-cli@1.6.1-alpha8
`npm run build`后，提示`[WARNING] 找不到插件：wepy-plugin-filemin。`
随后提示安装成功，但文件实际并没有被压缩，再次`npm run build`还是报错。
回退到1.6.0版本后，编译及压缩结果均正常。

```
> myproject@1.2.8 build F:\Development\workspace\leshare\leshare-food-weapp
> cross-env NODE_ENV=production wepy build --no-cache

ReferenceError: maxdeep is not defined
    at new pp (F:\Development\workspace\leshare\leshare-food-weapp\node_modules\pretty-data\pretty-data.js:54:11)
    at Object.<anonymous> (F:\Development\workspace\leshare\leshare-food-weapp\node_modules\pretty-data\pretty-data.js:334:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Development\workspace\leshare\leshare-food-weapp\node_modules\wepy-plugin-filemin\lib\index.js:9:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

**Comment by coolhwm** [comment]
@Gcaufy  这个问题求看看

**Comment by Gcaufy** [comment]
https://github.com/vkiryukhin/pretty-data/pull/3

**Comment by coolhwm** [comment]
感谢回复

**Comment by cuijiemmx** [comment]
@coolhwm 我自己fork了一个wepy-plugin-filemin修复了这个问题，通过以下命令安装
npm i cuijiemmx/wepy-plugin-filemin --save-dev

@Gcaufy 虽然是别人pretty-data的问题，但是wepy完全可以先修复这个问题，让东西work起来

**Comment by coolhwm** [comment]
@cuijiemmx  感谢，已经用上了

**Comment by ymqq** [comment]
perfect @cuijiemmx

**Comment by tinybright** [comment]
pretty-data.js:288
pp.prototype.xmlmin = function(text, preserveComments) {

	var str = preserveComments ? text
				   : text.replace(/\<![ \r\n\t]*(--([^\-]|[\r\n]|-[^\-])*--[ \r\n\t]*)\>/g,"");
	return  str.replace(/>\s{0,}</g,"><");
};

TypeError: Cannot read property 'replace' of null

**Comment by lisite** [comment]
> pretty-data.js:288
> 
> ```
> pp.prototype.xmlmin = function(text, preserveComments) {
> 
> 	var str = preserveComments ? text
> 				   : text.replace(/\<![ \r\n\t]*(--([^\-]|[\r\n]|-[^\-])*--[ \r\n\t]*)\>/g,"");
> 	return  str.replace(/>\s{0,}</g,"><");
> };
> ```
> TypeError: Cannot read property 'replace' of null

遇到了同样的问题

**Comment by sunshineprincessnt** [comment]
pp.prototype.xmlmin = function(text, preserveComments) {

	var str = preserveComments ? text
				   : text.replace(/\<![ \r\n\t]*(--([^\-]|[\r\n]|-[^\-])*--[ \r\n\t]*)\>/g,"");
	return  str.replace(/>\s{0,}</g,"><");
};
TypeError: Cannot read property 'replace' of null
请问 怎么解决？
