### ISSUE TITLE
windows下npm run dev 报错

### ISSUE THREAD

**Issue by flyfox11** [Tencent/wepy#911]
TypeError: Cannot read property 'charCodeAt' of undefined
    at Object.getIndent (D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\util.js:27
2:14)
    at D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-wpy.js:220:53
    at Object.resolveWpy (D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-w
py.js:235:11)
    at D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile.js:128:48
    at Array.forEach (native)
    at Object.findReference (D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compil
e.js:124:19)
    at D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile.js:361:40
    at Array.forEach (native)
    at Object.build (D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile.js:356
:19)
    at Command.<anonymous> (D:\Users\T00006331\AppData\Roaming\npm\node_modules\wepy-cli\lib\wepy.js
:243:27)
错误说的是，在wepy-cli/lib/util.js的272行  Cannot read property 'charCodeAt' of undefined

**Comment by gauseen** [comment]
解决了吗？我也遇到同样问题

**Comment by ideago** [comment]
我也是同样的问题，求解答

**Comment by 7hens** [comment]
wepy 的源码出错了，少了个非空判断，自己修改一下吧。

找到文件 AppData\Roaming\npm\node_modules\wepy-cli\lib\util.js，对变量 s 进行非空判断：

```javascript
        if (s) {
            if (s.charCodeAt(0) === 32 || s.charCodeAt(0) === 9) {
                indent.char = s[0];
            }
            while (s[i] === indent.char) {
                i++;
            }
        }
```

**Comment by HP-Ekrn** [comment]
今天早上突然出现的这个问题 晕死了
