### ISSUE TITLE
引入 `npm`  包  `crypto-browserify` ，控制台报错。

### ISSUE THREAD

**Issue by lwzhang** [Tencent/wepy#952]
## Description
引入 `npm`  包  `crypto-browserify` ，控制台报错。(只引入模块，无其他操作)

报错信息如下：
```
VM4655:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/safe-buffer/buffer.js" is not defined 
 Error: module "npm/safe-buffer/buffer.js" is not defined
    at require (http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15787)
    at http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15642
    at http://127.0.0.1:51628/appservice/npm/safe-buffer/index.js:2:14
    at require (http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15893)
    at http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15642
    at http://127.0.0.1:51628/appservice/npm/randombytes/browser.js:7:14
    at require (http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15893)
    at http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15642
    at http://127.0.0.1:51628/appservice/npm/crypto-browserify/index.js:3:80
    at require (http://127.0.0.1:51628/appservice/__dev__/WAService.js:18:15893)
```

**Comment by cuijiemmx** [comment]
@Gcaufy 不只是这个包有问题，在我的实际使用中，经常引入第三方package失败，概率在50%，举个例子，redux-saga引入后运行控制台报错，导致我不得不将第三方package中dist下编译好的**单文件js**复制到项目中引用，希望能花点时间研究下这个问题

**Comment by cuijiemmx** [comment]
@lwzhang 此类问题可以暂时以别的方式解决，具体方法是把node_modules/包名/dist中的umd版本的js文件复制到项目中引用，采用这种方式基本都能解决

**Comment by lwzhang** [comment]
@cuijiemmx `crypto-browserify`包没有dist。

**Comment by cuijiemmx** [comment]
@lwzhang 仔细看了下，你这个和我的问题确实不一样，buffer是nodejs中的东西，小程序内并不存在，不能直接拿来使用
