### ISSUE TITLE
wepy.createInnerAudioContext() 远程调试的时候会报错.

### ISSUE THREAD

**Issue by isunkui** [Tencent/wepy#968]
1）在组件的 onLoad 方法中，调用了下面方法
```
this.innerAudioContext = wepy.createInnerAudioContext()
this.innerAudioContext.onPause((res) => {
  console.log('onPause:', res)
  this.handleResetPlayStatus()
})
```
2）在开发者工具中，使用远程调试
![image](https://user-images.githubusercontent.com/10893176/36582124-2b4624da-18ab-11e8-971a-b55e3678e95c.png)

3) 手机扫完码后，控制台有概率会抛出如下异常

```
[publib]:3 appServiceSDKScriptError
createAudioInstance:fail Error: Failed To Send Sync; at wx.createInnerAudioContext
Error: createAudioInstance:fail Error: Failed To Send Sync
    at new e ([publib]:7:16378)
    at Function.i ([publib]:7:13215)
    at Object.<anonymous> ([publib]:4:8317)
    at Object.createInnerAudioContext (weapp:///npm/wepy/lib/app.js:245:48)
    at DfCard.onLoad (weapp:///components/card.js:108:47)
    at weapp:///npm/wepy/lib/component.js:230:56
    at Array.forEach (<anonymous>)
    at weapp:///npm/wepy/lib/component.js:229:49
    at Array.forEach (<anonymous>)
    at Index.$init (weapp:///npm/wepy/lib/component.js:225:22)
```
![image](https://user-images.githubusercontent.com/10893176/36582306-f2436c64-18ab-11e8-8e17-0c49c99f6acb.png)

请问上面这个问题是由远程调试导致的吗，在开发者工具里面，刷新访问则不会出现这个错误。

**Comment by devin1011** [comment]
请问如何解决的呢

**Comment by xuweikang** [comment]
@isunkui  怎么解决的

**Comment by Gcaufy** [comment]
试试这个
```
this.innerAudioContext = wepy.createInnerAudioContext()
this.innerAudioContext.onPause((res) => {
  console.log('onPause:', res)
  this.handleResetPlayStatus()
})
```

**Comment by wayne163** [comment]
目前远程调试调用录音还是会间歇性出现这个问题，请问怎么解决？
